In [26]:
import csv
import numpy as np

data = np.genfromtxt("BB_AirT_10_17.csv", delimiter=',')

print(data)


[[             nan              nan              nan              nan]
 [  2.01200000e+03   1.00000000e+01   1.00000000e+00   1.33300000e+01]
 [  2.01200000e+03   1.00000000e+01   2.00000000e+00   1.11100000e+01]
 ..., 
 [  2.01700000e+03   9.00000000e+00   2.80000000e+01   9.44000000e+00]
 [  2.01700000e+03   9.00000000e+00   2.90000000e+01   1.16700000e+01]
 [  2.01700000e+03   9.00000000e+00   3.00000000e+01   6.67000000e+00]]
